### ISSUE TITLE
feature request: smooth scrolling

### ISSUE THREAD

**Issue by Crusader-Boss** [itzbluebxrry/Project-Radon#3]
hey can you enable smooth scrolling by default for all websites. It would be a subtle yet great feature.

**Comment by itzbluebxrry** [comment]
The browser is powered by Edge WebView2 render engine. You could possibly enable some sort of flags in `radon://flags`.

**Comment by Crusader-Boss** [comment]
Ahh okay will check it out.

**Comment by itzbluebxrry** [comment]
Issue solved with WebView2 flags workaround.
